### ISSUE TITLE
3dpose-install.batのSSLエラー

### ISSUE THREAD

**Issue by listelin** [errno-mmd/mmdmatic#1]
3dpose-install.bat  
以下の行がエラーになる。
curl -L -O https://www.dropbox.com/s/e35qv3n6zlkouki/h36m.zip || goto die

-kを追加すれば解消する。
curl -L -k -O https://www.dropbox.com/s/e35qv3n6zlkouki/h36m.zip || goto die

**Comment by errno-mmd** [comment]
ご連絡ありがとうございます。
しかし手元では再現しません。
ブラウザ(chorome, Firefox)で見ても問題ないですし、SSL証明書もDigiCertの有効なものに見えます。
問題が起こるcurlのバージョンを教えていただけますか？

-k オプションは安全でない接続を許可してしまうので、できれば避けたいと思っています。

**Comment by listelin** [comment]
申し訳ありません。
有効期限切れとかかか、と思い雑な報告をしてお手数おかけしました。

カスペルスキーのネットワーク接続スキャン機能が有効になっていたことによるエラーでした。
カスペルスキーの当該保護機能を一時的に停止することで正常に動作することを確認しました。

類似事象が発生したときの参考として以下にエラー内容を記載します。

カスペルスキーインターネットセキュリティ2019保護機能によるエラー：
(mmdmat) C:\t\mmdmatic>3dpose-install.bat
　（中略）
(mmdmat) C:\t\mmdmatic\3d-pose-baseline-vmd\data>curl -L -O https://www.dropbox.com/s/e35qv3n6zlkouki/h36m.zip   || goto die
curl: (35) schannel: next InitializeSecurityContext failed: Unknown error (0x80092012) - 失効の関数は証明書の失効を確認 できませんでした。
ERROR

**Comment by errno-mmd** [comment]
エラーメッセージありがとうございます。
なるほど、このあたりに書かれている問題ですね。
https://qiita.com/Avocado/items/039846c0155fd58e8f91
https://github.com/desktop/desktop/issues/2471
カスペルスキーが自分の証明書を使ってくるからエラーが起きる、と。
（他の人のところでも起きそうだな・・・）
