### ISSUE TITLE
対処法について

### ISSUE THREAD

**Issue by suti-tasu** [errno-mmd/mmdmatic#11]
![2020-06-13](https://user-images.githubusercontent.com/51817697/84559344-b7d19a00-ad74-11ea-9667-cbc21c5361f4.png)
初めまして
このように表示されるのですがどうすればよいのでしょうか？
サンプルのものはできたのですがそれ以外のものができないです

**Comment by errno-mmd** [comment]
エラー内容に心当たりがなく、検索しても該当しそうな問題がヒットしないので、実際にその動画でエラーを再現させて調べないと手がかりがありません。差し支えなければエラーが起きた動画ファイルを頂けますか？

**Comment by errno-mmd** [comment]
ver1.03.05-1 で直ったかもしれません。よければ試してみてください。
https://github.com/errno-mmd/mmdmatic/releases/tag/ver1.03.05-1

**Comment by suti-tasu** [comment]
返信遅れて申し訳ありません
トレース成功しました
ありがとうございます
