### ISSUE TITLE
MMDmatic使わせて頂いております。

### ISSUE THREAD

**Issue by chicyann10** [errno-mmd/mmdmatic#14]
MMDmatic使わせて頂いております。

Ver2.0で最後の方でエラーが出てVMDファイルが作れません。

AssertionError: 
Found no NVIDIA driver on your system. Please check that you
have an NVIDIA GPU and installed a driver from
http://www.nvidia.com/Download/index.aspx

当方のPCはGPUが無いので、最初はver1.2を使ってましたがフォルダの中が空なのでver2.0を使ったら今度はVMDファイルだけ作れません。
AVIファイルとjsonファイルはフォルダに入ってるんですが、VMDファイルだけが作れず、エラーが出ます。

457.09-desktop-win10-64bit-international-dch-whqlとCUDAは入れてます。

後、ver1.2はGPU無し設定したのですが、上手く行きません。

何か良い方法は無いでしょうか？

**Comment by errno-mmd** [comment]
README.mdに書いてあるとおり、NVIDIA GPUが必要です。
NVIDIA GPUを搭載していないPCをお使いの場合はクラウド版( https://qiita.com/miu200521358/items/fb0a7bcf2764d7797e26 )をお勧めしています。

**Comment by chicyann10** [comment]
有難う😉👍️🎶御座います❗

クラウド版試して見ます。
