### ISSUE TITLE
setup.batが開けません

### ISSUE THREAD

**Issue by zertgeit** [errno-mmd/mmdmatic#16]
始めまして。
それを実行しようとダブルクリックすると、タスクバーに1秒ほど表示されすぐに消えます。
手伝ってください。Windows 10 64ビットです。

**Comment by errno-mmd** [comment]
とりあえず、READMEに書いてあるとおり Anaconda Prompt から実行して、エラーメッセージを確認するのはどうでしょうか？

**Comment by zertgeit** [comment]
解決しました。ありがとうございます。
