### ISSUE TITLE
System32のtftest1.pyが見つかりません

### ISSUE THREAD

**Issue by heavenisaplaceonearth** [errno-mmd/mmdmatic#4]
tensorflow-gpu-install.batにSystem32のtftest1.pyの呼び出しがあるんですが（失敗したらERROR2）

実際にはSystem32にtftest1.pyが作られません

管理者権限でやっても同じでした

とりあえずmmdmaticにあるtftest1.pyをSystem32に移して済みましたが

理由は分かりませんがtensorflow-gpu-install.batの最後にGPUが使えられないと表示されます

作業用PCなのでアンチウィルスなんて全然使用してないし

Windowやグラフィックドライバーも最新アップデートされてます

**Comment by errno-mmd** [comment]
tensorflow-gpu-install.bat を見ていただけば分かると思いますが、System32を指定していません。
https://github.com/errno-mmd/mmdmatic/blob/master/tensorflow-gpu-install.bat
お使いのpython環境の問題である可能性が高いと思いますが、Anacondaで入れたpythonが
実行されているのでしょうか？

GPUが使えない問題のほうはエラーメッセージを見ないと何とも言えません。
念のため確認ですが、PCにはNVIDIAのGPUが搭載されているのですよね？

**Comment by heavenisaplaceonearth** [comment]
なるほど「管理者として実行」してカレントディレクトリがSystem32に変更されているわけでした。

雑な質問して申し訳ありません。再インストールしてみます。
