### ISSUE TITLE
トレースがうまくいかないようです

### ISSUE THREAD

**Issue by heavenisaplaceonearth** [errno-mmd/mmdmatic#5]
Docker版(sm34829627)はトレースうまく行きましたが

ローカル版はトレースがうまくいかないようで

雑な質問ですがなぜこうなるのか心当たりはありませんか？

Docker版とローカル版の元になるコードが同じなら

性能もほぼ同じでは無ければならないと思いましたが

テストでトレースする[元の映像](https://youtu.be/f38jBUra5iQ)でテストしてみましたが

[Docker版のトレース映像](https://play-tv.kakao.com/v/404411678)と

[ローカル版のトレース映像](https://play-tv.kakao.com/v/404458742)の結果がかなり異なります。

ローカル版がうまく設置されていない可能性があり、再インストールしてやってみましたが結果は同じでした。

ニコニコ動画にアップロードしてくださった[サンプル映像](https://drive.google.com/open?id=1ccBzmONGNDbvmKa7SSqwMRPKQ3q-_6LG)で[ためしたら](https://play-tv.kakao.com/v/404459022)それは納得できる範囲でしたが、それ以外の別の映像では何もうまくいかないそうです。

モデルを変えてテストしてもトレース映像を何回も変えてテストしてもトレースがうまくいかないようです。

**Comment by errno-mmd** [comment]
play-tv.kakao.com に置かれた動画が再生されないので、どれぐらい差が出たのか分かりません。
Docker版とローカル版は、プログラムのバージョンが異なるので、結果が多少異なることはありえます。
ただし私の環境では、Docker版でトレースできていた動画が、mmdmaticでインストールしたローカル版でトレースできないようなケースは発生していません。

**Comment by heavenisaplaceonearth** [comment]
play-tv.kakao.comの動画がプレイ出来ないのはADblockerみたいな広告遮断フラグインのせいためだと思います。広告のあと動画が再生されるのでお手数ですが一時的にフラグインの作動を止めて、動画の右下にあるSKIPバトン押して広告をSKIPしてください。そうしたら、動画が再生されると思います。それでもできなかった場合YouTubeで再アップデートします。

念のため、CPUバージョンに切り替えてテストしてみましたが結果は同じでした

**Comment by errno-mmd** [comment]
手元のmmdmatic ver1.02.01-6環境で https://youtu.be/f38jBUra5iQ の動画を試しましたが、
2Dポーズ推定の結果で時々上半身が反転したりしています（腕の色が左右逆）。
![比較](https://user-images.githubusercontent.com/10104530/70369408-4bc13580-18fc-11ea-883f-8e0dcb0d72ee.png)
tf-pose-estimationのニューラルネットワークにとって認識が難しい映像なのだと思います。
Docker版（バージョンは？）でうまくいったのはtf-pose-estimationのバージョン差によるものかもしれませんが、不明です。
もしかして古いDocker版(tf-pose-estimationではなくOpenPoseを使っていた)を使っていませんか？

もしtf-pose-estimationについて詳しい議論がしたいのであれば、https://github.com/ildoonet/tf-pose-estimation のほうで聞くほうが良いと思います。

**Comment by heavenisaplaceonearth** [comment]
別のパソコンやっても結果が同じでした。おっしゃってる通りにDocker版はtf-pose-estimationではなくOpenPoseを使っていたのが結果の差の原因だと思われます。なるほど、勉強になりました。失礼いたしました。
