### ISSUE TITLE
Can't find file? During tf-pose-estimation step

### ISSUE THREAD

**Issue by Vesperindustrial** [errno-mmd/mmdmatic#7]
Hello, im using the sample video provided in google drive, and i get this error just after the tf-pose estimation part. The FileNotFoundError seems to be looking for a folder that the script is not creating? especially the 2_json one which is created as 2_json_02 but the json file does not exist in it. Likely due to the folder name?

frame:     0Traceback (most recent call last):
  File "run_video.py", line 81, in <module>
    image = TfPoseEstimator.draw_humans(image, humans, imgcopy=False, frame=frame, output_json_dir=args.write_json)
  File "N:\mmdmatic-ver1.03\tf-pose-estimation\tf_pose\estimator.py", line 453, in draw_humans
    with open(os.path.join(output_json_dir, '{0}_keypoints.json'.format(str(frame).zfill(12))), 'w') as outfile:
FileNotFoundError: [Errno 2] No such file or directory: 'N:\\mmdmatic-ver1.03\\motion_trace_bulk\\2_02/0/220_234820\\2_json\\000000000000_keypoints.json'

**Comment by Vesperindustrial** [comment]
Update: It seems like it is related to the DTTM/Datetime folder name, but i also find mmd can't load the resultant avi IYUV file (which just appears blank when played back) so im not sure if it is fully working still or not.

**Comment by errno-mmd** [comment]
Thanks for your report.
It seems that the problem is caused by a difference in date format. I'll try to fix it.

**Comment by errno-mmd** [comment]
Would you try this pre-release version of motion_trace_bulk?
https://github.com/errno-mmd/motion_trace_bulk/archive/date_format.zip

**Comment by Vesperindustrial** [comment]
Looks like it works now, thanks so much for fixing it! :D
