### ISSUE TITLE
エラーについて

### ISSUE THREAD

**Issue by reeetooo** [errno-mmd/mmdmatic#8]
こんにちは。この度はMMD自動トレースを行える素晴らしいシステムを開発頂きありがとうございます。
たいへん恐縮ながら、次の事を質問させて頂きたくご連絡しました。

AnacondaのWindows用インストーラを実行する際、Directory C:\users\user1\anaconda3 is not empty.
please choose a different location.
と表示されるので、違う場所に保存先を変更しました。

保存先　C:\Users\user1\anaconda3

その後、Pythonパッケージのインストールの項目まで進んだのですが、package-install.batの実行の際に

C:\mmdmatic-master>call activate mmdmat   || goto die
Could not find conda environment: mmdmat
You can list all discoverable environments with `conda info --envs`.

ERROR
続行するには何かキーを押してください . . .

というエラーが出てしまいます。

自動トレースの各ツールのインストール以降の項目を実行しても同じエラーが出てしまいます。

ファイルの保存先が間違っているのか何かインストールし忘れている見落としがあるのかわかりません。

もしよろしければ、お手隙の際にご返信頂ければ大変有り難いです。
よろしくお願い致します。

**Comment by errno-mmd** [comment]
そのパターンだと、package-install.bat の前に tensorflow-gpu-install.bat (tensorflow-install.bat)でエラーが起きそうなものですが、エラーなしで完了したのでしょうか？
まずは tensorflow-gpu-install.bat (tensorflow-install.bat)からやり直したほうがいいでしょう。

念のために聞きますが、最初からAnacondaがインストール済みだったということはありませんか？

**Comment by reeetooo** [comment]
tensorflow-install.batを実行すると次のように結果が出ました

C:\mmdmatic-master>call conda create -n mmdmat   || goto die
WARNING: A directory already exists at the target location 'C:\Anaconda3\envs\mm
dmat'
but it is not a conda environment.
Continue creating environment (y/[n])?

存在するけれどcondaに適応する環境ではないという風に書かれています。

**Comment by errno-mmd** [comment]
そこはREADMEに書いてあるとおり、
実行中にもし "Continue creating environment (y/[n])?" と聞かれたら、y を入力してエンターキーを押します。

**Comment by reeetooo** [comment]
遅くなり申し訳ございません。

やはりエラーが出る様です
ensorflow-install.batを実行すると

Preparing transaction: done
Verifying transaction: done
Executing transaction: done

(mmdmat) C:\mmdmatic-master>python tftest1.py   || goto die
Traceback (most recent call last):
  File "tftest1.py", line 2, in <module>
    import tensorflow as tf
ModuleNotFoundError: No module named 'tensorflow'
ERROR
続行するには何かキーを押してください . . .

となります。

**Comment by errno-mmd** [comment]
何か変なことをやってAnacondaの環境を壊したのではないかと思いますが。

もう一度書きます。
念のために聞きますが、最初からAnacondaがインストール済みだったということはありませんか？

**Comment by reeetooo** [comment]
たいへん申し訳ございません。
日を跨いだもので記憶が曖昧でした。
Anacondaはインストール済みだったと思います。

**Comment by errno-mmd** [comment]
やはりそうでしたか。おそらく2つのAnacondaの間で不整合が起きているのではないかと思います。
もし差し支えなければ、一度Anacondaを(2つあれば2つとも)アンインストールし、
さらにAnacondaが使っていたフォルダ(C:\users\user1\anaconda3、C:\Anaconda3など)も消してからインストールし直したほうが確実だと思います。

**Comment by reeetooo** [comment]
お手数おかけして申し訳ありませんでした。
指南頂いた方法を試させて頂きます。
ありがとうございます。
