### ISSUE TITLE
MotionTraceBulk 実行時にエラーが発生します

### ISSUE THREAD

**Issue by thilg28** [errno-mmd/mmdmatic#9]
はじめまして

突然のコメント失礼します。

mmd自動トレース導入（https://www.nicovideo.jp/watch/sm35683725)の
手順に従い、バッチファイル”MotionTraceBulk”を実行した際に下記エラーメッセージが
表示されてしまいます。どうしたらよろしいでしょうか

エラーメッセージ↓
ModuleNotFoundError: No module named 'tensorflow.contrib'

windows10　pro
CUDA10
cuDNN v7.6.5
GPUがNAVIDIAなので、tensorflow-gpu-install　しています。

バッチファイル実行後のスクリーンショットも添付します
![conda](https://user-images.githubusercontent.com/65196492/81617059-a9aff700-941f-11ea-9228-3e826bbb8341.JPG)

**Comment by errno-mmd** [comment]
TensorFlow 2.x系で動かしたときのエラーに見えるのですが、tensorflowをアップグレードしませんでしたか？
Anaconda promptで
`activate mmdmat`
`conda install -y tensorflow-gpu=1.14.0`
で直るのではないかと思います。

**Comment by thilg28** [comment]
連絡ありがとうございます

AnacondaNAVIGATORで確認したところ確かに2.1でした。
動画に合わせてver1.02.01-4をインストールしたためと思われます

uninstall.bat使用してフォルダも削除して
mmdmatic-ver1.03-3で作業手順を行ったところ
下記のようなアラームが出ました。

RuntimeError: The size of tensor a (45) must match the size of tensor b (44) at non-singleton dimension 2

他　MotionTraceBulk.batを編集で開いてみて気づいたのですがフォルダ内にBulk3dPoseGan.batが
ありませんでした。
mtbulk-install.batを実行しなおしたほうがよろしいでしょうか

以下アラーム発生時のスクリーンショットです。赤線部がそのエラーになります
![image](https://user-images.githubusercontent.com/65196492/81804627-630fe900-9554-11ea-9b42-492e2d851423.png)

**Comment by errno-mmd** [comment]
サンプル動画(https://drive.google.com/open?id=1ccBzmONGNDbvmKa7SSqwMRPKQ3q-_6LG)でも駄目でしたか？
どうも使っているツール(mannequinchallenge-vmd)の問題で、アスペクト比が16:9以外の動画だとエラーが起こるようなのです。

**Comment by thilg28** [comment]
サンプル動画でできました！

ありがとうございます！
